from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FightForShikigamiAssets: 


	# Image Rule Assets
	# 庭院右侧挂牌列「为崽而战」入口 
	I_FFS_ENTRY = RuleImage(roi_front=(1174,283,58,60), roi_back=(1150,140,110,430), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_entry.png")
	# 挂牌列底部刷新（循环箭头），找不到入口时点它换一批 
	I_FFS_REFRESH = RuleImage(roi_front=(1176,518,44,40), roi_back=(1150,460,110,130), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_refresh.png")
	# 活动主界面「八百八狸盛宴」入口（竖排旗，左右两个未解锁的注意区分） 
	I_FFS_BANQUET = RuleImage(roi_front=(452,150,40,235), roi_back=(440,138,64,260), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_banquet.png")
	# 六边形地图页标题「八百八狸·第一宴」 
	I_FFS_MAP_TITLE = RuleImage(roi_front=(505,8,262,36), roi_back=(505,8,262,36), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_map_title.png")
	# 战斗入口页标题「妖怪退治」 
	I_FFS_BATTLE_TITLE = RuleImage(roi_front=(404,20,112,24), roi_back=(404,20,112,24), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_battle_title.png")
	# 战斗入口页右下角「退治」按钮 
	I_FFS_RETREAT = RuleImage(roi_front=(1116,600,122,38), roi_back=(1100,575,160,80), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_retreat.png")
	# 「每日消耗上限」文字 
	I_FFS_DAILY_LIMIT = RuleImage(roi_front=(1117,672,128,18), roi_back=(1117,672,128,18), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_daily_limit.png")
	# 屏幕中部提示「体力消耗已达上限」——次数耗尽的终止信号 
	I_FFS_STAMINA_LIMIT = RuleImage(roi_front=(535,228,210,30), roi_back=(500,205,300,75), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_stamina_limit.png")
	# 活动内左上角返回按钮（鸟居框内左箭头）——活动主界面 / 战斗入口页用这个 
	I_FFS_BACK = RuleImage(roi_front=(6,6,84,72), roi_back=(0,0,116,96), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_back.png")
	# 地图页左上角返回按钮（圆形深色按钮 + 金色弧形箭头）——与上面那个**完全不同**，必须分开 
	I_FFS_BACK_MAP = RuleImage(roi_front=(8,4,54,54), roi_back=(0,0,90,80), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_back_map.png")
	# 地图中央 POI 的「退治完成」标记——用于区分「本期已打完」和「检测异常」 
	I_FFS_DONE = RuleImage(roi_front=(584,476,116,28), roi_back=(560,460,170,60), threshold=0.8, method="Template matching", file="./tasks/FightForShikigami/ffs/ffs_done.png")


	# Ocr Rule Assets
	# 每日消耗上限计数（已消耗/上限） 
	O_FFS_DAILY_COST = RuleOcr(roi=(1155,695,85,20), area=(1155,695,85,20), mode="DigitCounter", method="Default", keyword="", name="daily_cost")
	# 地图页顶部状态行：已开启时是「本宴X时X分X秒后结束」，未开启时是「本宴X分X秒后开启挑战」 
	O_FFS_BANQUET_STATUS = RuleOcr(roi=(500,42,280,34), area=(500,42,280,34), mode="Single", method="Default", keyword="", name="banquet_status")

